# Formulae every Mac should have; update.zsh offers to install them with `brew bundle`.
# Machine-specific ones stay out of here: install those with `brew install`.

brew "git"
# Scans commits in the dotfiles pre-commit hook
brew "gitleaks"
# The default editor (see $EDITOR in ~/.zshrc)
brew "neovim"
